from pathlib import Path
from decouple import config

BASE_DIR = Path(__file__).resolve().parent.parent

# ── ML Model paths ────────────────────────────────────────────────────────────
# Trained scikit-learn crop model files (generated by train_crop_model.py)
ML_MODELS_DIR       = BASE_DIR / 'models_ml'
CROP_MODEL_PATH     = ML_MODELS_DIR / 'crop_model.pkl'
LABEL_ENCODER_PATH  = ML_MODELS_DIR / 'label_encoder.pkl'

# Hugging Face model ID for plant disease detection
# Downloaded automatically on first server start (~50 MB, cached locally)
HF_DISEASE_MODEL_ID = config(
    'HF_DISEASE_MODEL_ID',
    default='linkanjarad/mobilenet_v2_1.0_224-plant-disease-identification'
)

SECRET_KEY = config('SECRET_KEY', default='django-insecure-change-me')

DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='*').split(',')

INSTALLED_APPS = [
    # Django MongoDB compatible apps only
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'greenguardian.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'greenguardian.wsgi.application'

# PostgreSQL database (OLD - commented out)
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': config('DB_NAME', default='greenguardian'),
#         'USER': config('DB_USER', default='postgres'),
#         'PASSWORD': config('DB_PASSWORD', default='ebisa1234'),
#         'HOST': config('DB_HOST', default='localhost'),
#         'PORT': config('DB_PORT', default='5432'),
#     }
# }

# MongoDB database (Official Django MongoDB Backend for Django 5)
DATABASES = {
    'default': {
        'ENGINE': 'django_mongodb_backend',
        'NAME': config('MONGO_DB_NAME', default='greenguardian'),
        'CLIENT': {
            'host': config('MONGO_URI', default='mongodb://localhost:27017/'),
        }
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise static file serving
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

DEFAULT_AUTO_FIELD = 'django_mongodb_backend.fields.ObjectIdAutoField'

# CORS — allow Next.js dev and prod origins
# Temporarily allow all origins for debugging
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='http://localhost:3000,http://127.0.0.1:3000,https://green-guardian-five.vercel.app'
).split(',')

# Only use CORS_ALLOW_ALL_ORIGINS in development
# if DEBUG:
#     CORS_ALLOW_ALL_ORIGINS = True
# else:
#     CORS_ALLOW_ALL_ORIGINS = False
#     # In production, ensure Vercel origin is allowed
#     if 'https://green-guardian-five.vercel.app' not in CORS_ALLOWED_ORIGINS:
#         CORS_ALLOWED_ORIGINS.append('https://green-guardian-five.vercel.app')

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [],  # No auth needed for public API
    'UNAUTHENTICATED_USER': None,  # Don't use Django User model
}
